[package]
name = "reconnect-tp"
version = "0.1.0"
authors = ["Shunichi Ikegami <sike.tm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
